[package]
name = "rust_3d"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
dashmap = "6.1.0"
minifb = "0.27.0"
rayon = "1.10.0"
serde = {version="1.0.217" , features = ["derive"]}
serde_json = "1.0.134"
tobj = "4.0.2"
